services:
  node_exporter:
    image: prom/node-exporter:master
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    # ports:
    #   - "9100:9100"
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
